### ISSUE TITLE
Qiita公式と同じ投稿URLを利用してほしい

### ISSUE THREAD

**Issue by gulping** [suzuki86/qrank-apiserver#19]
ユースケース
---
QiitaやQrankやはてブなど複数サイトで、Qiita内の見たい記事を探して読んでいる。
すると、既読の投稿もQrank上に表示されるが、それらは飛ばして、まだ読んでいない投稿のみを読みたい。
Qrank上では投稿タイトルの情報しかないため、既読投稿がどれか分かりにくい。
CSSの`:visited`擬似クラスにスタイルを当てることで、既読かどうかを判別しやすくできるが、
それを有効にするにもURLが一致している必要がある。
Qrank上の各投稿へのURLはQiitaの標準のURLと違うものになっているため、一致させてほしい。

概要
---
Qrank上の各投稿へのURLは

```
http://qiita.com/items/{投稿ID}
```
の形になっているが、Qiitaの標準の

```
http://qiita.com/{ユーザID}/items/{投稿ID}
```
の形にしてほしい。

**Comment by suzuki86** [comment]
@gulping ありがとうございます:smile: 修正可能と思いますが、詳細は追って確認します。

**Comment by suzuki86** [comment]
@gulping 遅くなりましたが対応完了しました！
