### ISSUE TITLE
スパムなどをなるべく弾いてほしい

### ISSUE THREAD

**Issue by gulping** [suzuki86/qrank-apiserver#34]
24時間のはてブ数ランキングなどは指標の母数が少ないため工作の影響を受けやすく、スパム投稿がランクインすることがまれにある。
ランキング枠は20しかないため、スパムが占めているぶん有用な投稿を読めなくなってしまう。
そのため、スパムをなるべく弾いてほしい。

完全に防げるようなものではないので適当で十分です……。

- 考えうる措置例
    - 限定公開(`private: true`)のものは弾く
    - ソート時に第2キーを利用する
      - もう一方の指標(はてブならいいね)でソート
      - タイトルや内容に日本語を含まないものの順位を下げる
        - 非日本語のスパムが多いため

-----

例：

2018/4/910:22
はてブ / 24時間

非スパム: 3投稿
未削除スパム: 10投稿
削除済スパム(青リンク): 7投稿
![ed41fcd31fdf92c9b77322bc307b3fdf](https://user-images.githubusercontent.com/27839122/38475063-254acaa6-3be0-11e8-8bf4-ca190ba10617.png)

2018/4/12 10:14
はてブ / 24時間

非スパム: 3投稿
未削除スパム: 17投稿
![d60540f53c981d1d7cee68c75b1dd665](https://user-images.githubusercontent.com/27839122/38651200-d7b1907e-3e3a-11e8-95d4-7c46d82203c5.png)

**Comment by suzuki86** [comment]
@gulping 
スパムのフィルタリング自体は Qiita の運営の方々が行って頂いているので、Private になっていたらランキングから消すという方法が現実的かもしれません。現在は、記事が削除されていてもランキングから消す機能がないので、それも合わせて対応したいと思います！

**Comment by gulping** [comment]
未削除スパムが多いのを気にしていましたが、数日前にQiitaのほうのフィルタリングが強化されたので
限定公開をフィルタリングするだけで全く問題なさそうです！

**Comment by suzuki86** [comment]
@gulping なるほど、それは助かります！

**Comment by gulping** [comment]
現在も同様の問題があるのですがサスペンドされたユーザの記事(?)のフィルタリングなどは可能でしょうか…

**Comment by suzuki86** [comment]
@gulping 削除されたユーザー/投稿を消すのはうっすらと考えていました。こちらも別 issue として立てておきます 🙏
